name: Django DevSecOps Pipeline

on:
  push:
    branches: [master]

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pip install bandit safety
   #--   - name: Security scan
   #--     run: safety check --full-report

  deploy-to-azure:
    needs: test-and-scan
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Critical: Install dependencies on Azure
      - name: Install dependencies on Azure
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
          pip install gunicorn

      # Add this new step to set PYTHONPATH
      - name: Set Python path
        run: |
          echo "PYTHONPATH=/home/site/wwwroot/DjangoWebProject3" >> $GITHUB_ENV
          
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: django-app-azure
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          # Update startup command with path fix
          startup-command: "gunicorn DjangoWebProject3.wsgi:application --pythonpath /home/site/wwwroot/DjangoWebProject3 --bind=0.0.0.0"
